export const CSS_VARS = {
  "--font-family": `var(--fontStack-sansSerif, -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji")`,
  "--button-danger-fgColor-rest": "var(----button-danger-fgColor-rest)",
  "--button-primary-bgColor-active": "var(----button-primary-bgColor-active)",
  "--button-primary-bgColor-disabled":
    "var(----button-primary-bgColor-disabled)",
  "--button-primary-bgColor-hover": "var(----button-primary-bgColor-hover)",
  "--button-primary-borderColor-disabled":
    "var(----button-primary-borderColor-disabled)",
  "--color-ansi-cyan": "var(----color-ansi-cyan)",
  "--color-ansi-cyan-bright": "var(----color-ansi-cyan-bright)",
  "--control-checked-bgColor-active": "var(----control-checked-bgColor-active)",
  "--control-checked-bgColor-hover": "var(----control-checked-bgColor-hover)",
  "--fgColor-accent": "var(----fgColor-accent)",
  "--reactionButton-selected-bgColor-hover":
    "var(----reactionButton-selected-bgColor-hover)",
  "--avatar-shadow": "var(----avatar-shadow)",
  "--avatarStack-fade-bgColor-default":
    "var(----avatarStack-fade-bgColor-default)",
  "--avatarStack-fade-bgColor-muted": "var(----avatarStack-fade-bgColor-muted)",
  "--bgColor-accent-emphasis": "var(----bgColor-accent-emphasis)",
  "--bgColor-accent-muted": "var(----bgColor-accent-muted)",
  "--bgColor-attention-emphasis": "var(----bgColor-attention-emphasis)",
  "--bgColor-attention-muted": "var(----bgColor-attention-muted)",
  "--bgColor-danger-emphasis": "var(----bgColor-danger-emphasis)",
  "--bgColor-danger-muted": "var(----bgColor-danger-muted)",
  "--bgColor-default": "var(----bgColor-default)",
  "--bgColor-disabled": "var(----bgColor-disabled)",
  "--bgColor-done-emphasis": "var(----bgColor-done-emphasis)",
  "--bgColor-done-muted": "var(----bgColor-done-muted)",
  "--bgColor-emphasis": "var(----bgColor-emphasis)",
  "--bgColor-muted": "var(----bgColor-muted)",
  "--bgColor-neutral-emphasis": "var(----bgColor-neutral-emphasis)",
  "--bgColor-neutral-muted": "var(----bgColor-neutral-muted)",
  "--bgColor-severe-emphasis": "var(----bgColor-severe-emphasis)",
  "--bgColor-severe-muted": "var(----bgColor-severe-muted)",
  "--bgColor-sponsors-emphasis": "var(----bgColor-sponsors-emphasis)",
  "--bgColor-sponsors-muted": "var(----bgColor-sponsors-muted)",
  "--bgColor-success-emphasis": "var(----bgColor-success-emphasis)",
  "--bgColor-success-muted": "var(----bgColor-success-muted)",
  "--bgColor-transparent": "var(----bgColor-transparent)",
  "--borderColor-accent-emphasis": "var(----borderColor-accent-emphasis)",
  "--borderColor-accent-muted": "var(----borderColor-accent-muted)",
  "--borderColor-attention-emphasis": "var(----borderColor-attention-emphasis)",
  "--borderColor-attention-muted": "var(----borderColor-attention-muted)",
  "--borderColor-danger-emphasis": "var(----borderColor-danger-emphasis)",
  "--borderColor-danger-muted": "var(----borderColor-danger-muted)",
  "--borderColor-default": "var(----borderColor-default)",
  "--borderColor-disabled": "var(----borderColor-disabled)",
  "--borderColor-done-emphasis": "var(----borderColor-done-emphasis)",
  "--borderColor-done-muted": "var(----borderColor-done-muted)",
  "--borderColor-emphasis": "var(----borderColor-emphasis)",
  "--borderColor-severe-emphasis": "var(----borderColor-severe-emphasis)",
  "--borderColor-severe-muted": "var(----borderColor-severe-muted)",
  "--borderColor-sponsors-emphasis": "var(----borderColor-sponsors-emphasis)",
  "--borderColor-sponsors-muted": "var(----borderColor-sponsors-muted)",
  "--borderColor-success-emphasis": "var(----borderColor-success-emphasis)",
  "--borderColor-success-muted": "var(----borderColor-success-muted)",
  "--borderColor-transparent": "var(----borderColor-transparent)",
  "--button-danger-bgColor-hover": "var(----button-danger-bgColor-hover)",
  "--button-danger-iconColor-rest": "var(----button-danger-iconColor-rest)",
  "--button-danger-shadow-selected": "var(----button-danger-shadow-selected)",
  "--button-default-shadow-resting": "var(----button-default-shadow-resting)",
  "--button-inactive-bgColor": "var(----button-inactive-bgColor)",
  "--button-inactive-fgColor": "var(----button-inactive-fgColor)",
  "--button-invisible-bgColor-disabled":
    "var(----button-invisible-bgColor-disabled)",
  "--button-invisible-borderColor-disabled":
    "var(----button-invisible-borderColor-disabled)",
  "--button-outline-bgColor-active": "var(----button-outline-bgColor-active)",
  "--button-outline-bgColor-rest": "var(----button-outline-bgColor-rest)",
  "--button-outline-fgColor-disabled":
    "var(----button-outline-fgColor-disabled)",
  "--button-outline-fgColor-hover": "var(----button-outline-fgColor-hover)",
  "--button-outline-fgColor-rest": "var(----button-outline-fgColor-rest)",
  "--button-outline-shadow-selected": "var(----button-outline-shadow-selected)",
  "--button-primary-shadow-selected": "var(----button-primary-shadow-selected)",
  "--button-star-iconColor": "var(----button-star-iconColor)",
  "--buttonCounter-danger-bgColor-rest":
    "var(----buttonCounter-danger-bgColor-rest)",
  "--buttonCounter-default-bgColor-rest":
    "var(----buttonCounter-default-bgColor-rest)",
  "--buttonCounter-outline-bgColor-hover":
    "var(----buttonCounter-outline-bgColor-hover)",
  "--buttonCounter-outline-bgColor-rest":
    "var(----buttonCounter-outline-bgColor-rest)",
  "--buttonCounter-outline-fgColor-disabled":
    "var(----buttonCounter-outline-fgColor-disabled)",
  "--buttonCounter-outline-fgColor-hover":
    "var(----buttonCounter-outline-fgColor-hover)",
  "--buttonCounter-outline-fgColor-rest":
    "var(----buttonCounter-outline-fgColor-rest)",
  "--buttonCounter-primary-bgColor-rest":
    "var(----buttonCounter-primary-bgColor-rest)",
  "--codeMirror-syntax-fgColor-comment":
    "var(----codeMirror-syntax-fgColor-comment)",
  "--codeMirror-syntax-fgColor-constant":
    "var(----codeMirror-syntax-fgColor-constant)",
  "--codeMirror-syntax-fgColor-entity":
    "var(----codeMirror-syntax-fgColor-entity)",
  "--codeMirror-syntax-fgColor-keyword":
    "var(----codeMirror-syntax-fgColor-keyword)",
  "--codeMirror-syntax-fgColor-storage":
    "var(----codeMirror-syntax-fgColor-storage)",
  "--codeMirror-syntax-fgColor-string":
    "var(----codeMirror-syntax-fgColor-string)",
  "--codeMirror-syntax-fgColor-support":
    "var(----codeMirror-syntax-fgColor-support)",
  "--codeMirror-syntax-fgColor-variable":
    "var(----codeMirror-syntax-fgColor-variable)",
  "--color-ansi-black": "var(----color-ansi-black)",
  "--color-ansi-black-bright": "var(----color-ansi-black-bright)",
  "--color-ansi-blue": "var(----color-ansi-blue)",
  "--color-ansi-blue-bright": "var(----color-ansi-blue-bright)",
  "--color-ansi-gray": "var(----color-ansi-gray)",
  "--color-ansi-green": "var(----color-ansi-green)",
  "--color-ansi-green-bright": "var(----color-ansi-green-bright)",
  "--color-ansi-magenta": "var(----color-ansi-magenta)",
  "--color-ansi-magenta-bright": "var(----color-ansi-magenta-bright)",
  "--color-ansi-red": "var(----color-ansi-red)",
  "--color-ansi-red-bright": "var(----color-ansi-red-bright)",
  "--color-ansi-white": "var(----color-ansi-white)",
  "--color-ansi-yellow": "var(----color-ansi-yellow)",
  "--color-ansi-yellow-bright": "var(----color-ansi-yellow-bright)",
  "--color-prettylights-syntax-brackethighlighter-angle":
    "var(----color-prettylights-syntax-brackethighlighter-angle)",
  "--color-prettylights-syntax-brackethighlighter-unmatched":
    "var(----color-prettylights-syntax-brackethighlighter-unmatched)",
  "--color-prettylights-syntax-carriage-return-bg":
    "var(----color-prettylights-syntax-carriage-return-bg)",
  "--color-prettylights-syntax-carriage-return-text":
    "var(----color-prettylights-syntax-carriage-return-text)",
  "--color-prettylights-syntax-comment":
    "var(----color-prettylights-syntax-comment)",
  "--color-prettylights-syntax-constant":
    "var(----color-prettylights-syntax-constant)",
  "--color-prettylights-syntax-constant-other-reference-link":
    "var(----color-prettylights-syntax-constant-other-reference-link)",
  "--color-prettylights-syntax-entity":
    "var(----color-prettylights-syntax-entity)",
  "--color-prettylights-syntax-entity-tag":
    "var(----color-prettylights-syntax-entity-tag)",
  "--color-prettylights-syntax-invalid-illegal-bg":
    "var(----color-prettylights-syntax-invalid-illegal-bg)",
  "--color-prettylights-syntax-invalid-illegal-text":
    "var(----color-prettylights-syntax-invalid-illegal-text)",
  "--color-prettylights-syntax-keyword":
    "var(----color-prettylights-syntax-keyword)",
  "--color-prettylights-syntax-markup-bold":
    "var(----color-prettylights-syntax-markup-bold)",
  "--color-prettylights-syntax-markup-changed-bg":
    "var(----color-prettylights-syntax-markup-changed-bg)",
  "--color-prettylights-syntax-markup-changed-text":
    "var(----color-prettylights-syntax-markup-changed-text)",
  "--color-prettylights-syntax-markup-deleted-bg":
    "var(----color-prettylights-syntax-markup-deleted-bg)",
  "--color-prettylights-syntax-markup-deleted-text":
    "var(----color-prettylights-syntax-markup-deleted-text)",
  "--color-prettylights-syntax-markup-heading":
    "var(----color-prettylights-syntax-markup-heading)",
  "--color-prettylights-syntax-markup-ignored-bg":
    "var(----color-prettylights-syntax-markup-ignored-bg)",
  "--color-prettylights-syntax-markup-ignored-text":
    "var(----color-prettylights-syntax-markup-ignored-text)",
  "--color-prettylights-syntax-markup-inserted-bg":
    "var(----color-prettylights-syntax-markup-inserted-bg)",
  "--color-prettylights-syntax-markup-inserted-text":
    "var(----color-prettylights-syntax-markup-inserted-text)",
  "--color-prettylights-syntax-markup-italic":
    "var(----color-prettylights-syntax-markup-italic)",
  "--color-prettylights-syntax-markup-list":
    "var(----color-prettylights-syntax-markup-list)",
  "--color-prettylights-syntax-meta-diff-range":
    "var(----color-prettylights-syntax-meta-diff-range)",
  "--color-prettylights-syntax-storage-modifier-import":
    "var(----color-prettylights-syntax-storage-modifier-import)",
  "--color-prettylights-syntax-string":
    "var(----color-prettylights-syntax-string)",
  "--color-prettylights-syntax-string-regexp":
    "var(----color-prettylights-syntax-string-regexp)",
  "--color-prettylights-syntax-sublimelinter-gutter-mark":
    "var(----color-prettylights-syntax-sublimelinter-gutter-mark)",
  "--color-prettylights-syntax-variable":
    "var(----color-prettylights-syntax-variable)",
  "--contribution-default-bgColor-0": "var(----contribution-default-bgColor-0)",
  "--contribution-default-bgColor-1": "var(----contribution-default-bgColor-1)",
  "--contribution-default-bgColor-2": "var(----contribution-default-bgColor-2)",
  "--contribution-default-bgColor-3": "var(----contribution-default-bgColor-3)",
  "--contribution-default-bgColor-4": "var(----contribution-default-bgColor-4)",
  "--contribution-default-borderColor-0":
    "var(----contribution-default-borderColor-0)",
  "--contribution-halloween-bgColor-1":
    "var(----contribution-halloween-bgColor-1)",
  "--contribution-halloween-bgColor-2":
    "var(----contribution-halloween-bgColor-2)",
  "--contribution-halloween-bgColor-3":
    "var(----contribution-halloween-bgColor-3)",
  "--contribution-halloween-bgColor-4":
    "var(----contribution-halloween-bgColor-4)",
  "--contribution-winter-bgColor-1": "var(----contribution-winter-bgColor-1)",
  "--contribution-winter-bgColor-2": "var(----contribution-winter-bgColor-2)",
  "--contribution-winter-bgColor-3": "var(----contribution-winter-bgColor-3)",
  "--contribution-winter-bgColor-4": "var(----contribution-winter-bgColor-4)",
  "--control-bgColor-active": "var(----control-bgColor-active)",
  "--control-bgColor-hover": "var(----control-bgColor-hover)",
  "--control-bgColor-rest": "var(----control-bgColor-rest)",
  "--control-borderColor-selected": "var(----control-borderColor-selected)",
  "--control-checked-borderColor-active":
    "var(----control-checked-borderColor-active)",
  "--control-checked-borderColor-hover":
    "var(----control-checked-borderColor-hover)",
  "--control-danger-fgColor-hover": "var(----control-danger-fgColor-hover)",
  "--control-transparent-bgColor-active":
    "var(----control-transparent-bgColor-active)",
  "--control-transparent-bgColor-hover":
    "var(----control-transparent-bgColor-hover)",
  "--control-transparent-bgColor-rest":
    "var(----control-transparent-bgColor-rest)",
  "--control-transparent-bgColor-selected":
    "var(----control-transparent-bgColor-selected)",
  "--control-transparent-borderColor-active":
    "var(----control-transparent-borderColor-active)",
  "--control-transparent-borderColor-hover":
    "var(----control-transparent-borderColor-hover)",
  "--control-transparent-borderColor-rest":
    "var(----control-transparent-borderColor-rest)",
  "--controlTrack-bgColor-active": "var(----controlTrack-bgColor-active)",
  "--controlTrack-bgColor-hover": "var(----controlTrack-bgColor-hover)",
  "--controlTrack-bgColor-rest": "var(----controlTrack-bgColor-rest)",
  "--counter-borderColor": "var(----counter-borderColor)",
  "--data-auburn-color-emphasis": "var(----data-auburn-color-emphasis)",
  "--data-auburn-color-muted": "var(----data-auburn-color-muted)",
  "--data-blue-color-emphasis": "var(----data-blue-color-emphasis)",
  "--data-blue-color-muted": "var(----data-blue-color-muted)",
  "--data-brown-color-emphasis": "var(----data-brown-color-emphasis)",
  "--data-brown-color-muted": "var(----data-brown-color-muted)",
  "--data-coral-color-emphasis": "var(----data-coral-color-emphasis)",
  "--data-coral-color-muted": "var(----data-coral-color-muted)",
  "--data-gray-color-emphasis": "var(----data-gray-color-emphasis)",
  "--data-gray-color-muted": "var(----data-gray-color-muted)",
  "--data-green-color-emphasis": "var(----data-green-color-emphasis)",
  "--data-green-color-muted": "var(----data-green-color-muted)",
  "--data-lemon-color-emphasis": "var(----data-lemon-color-emphasis)",
  "--data-lemon-color-muted": "var(----data-lemon-color-muted)",
  "--data-lime-color-emphasis": "var(----data-lime-color-emphasis)",
  "--data-lime-color-muted": "var(----data-lime-color-muted)",
  "--data-olive-color-emphasis": "var(----data-olive-color-emphasis)",
  "--data-olive-color-muted": "var(----data-olive-color-muted)",
  "--data-orange-color-emphasis": "var(----data-orange-color-emphasis)",
  "--data-orange-color-muted": "var(----data-orange-color-muted)",
  "--data-pine-color-emphasis": "var(----data-pine-color-emphasis)",
  "--data-pine-color-muted": "var(----data-pine-color-muted)",
  "--data-pink-color-emphasis": "var(----data-pink-color-emphasis)",
  "--data-pink-color-muted": "var(----data-pink-color-muted)",
  "--data-plum-color-emphasis": "var(----data-plum-color-emphasis)",
  "--data-plum-color-muted": "var(----data-plum-color-muted)",
  "--data-purple-color-emphasis": "var(----data-purple-color-emphasis)",
  "--data-purple-color-muted": "var(----data-purple-color-muted)",
  "--data-red-color-emphasis": "var(----data-red-color-emphasis)",
  "--data-red-color-muted": "var(----data-red-color-muted)",
  "--data-teal-color-emphasis": "var(----data-teal-color-emphasis)",
  "--data-teal-color-muted": "var(----data-teal-color-muted)",
  "--data-yellow-color-emphasis": "var(----data-yellow-color-emphasis)",
  "--data-yellow-color-muted": "var(----data-yellow-color-muted)",
  "--diffBlob-additionNum-bgColor": "var(----diffBlob-additionNum-bgColor)",
  "--diffBlob-additionWord-bgColor": "var(----diffBlob-additionWord-bgColor)",
  "--diffBlob-deletionNum-bgColor": "var(----diffBlob-deletionNum-bgColor)",
  "--diffBlob-deletionWord-bgColor": "var(----diffBlob-deletionWord-bgColor)",
  "--diffBlob-hunkNum-bgColor-rest": "var(----diffBlob-hunkNum-bgColor-rest)",
  "--display-auburn-bgColor-emphasis":
    "var(----display-auburn-bgColor-emphasis)",
  "--display-auburn-bgColor-muted": "var(----display-auburn-bgColor-muted)",
  "--display-auburn-borderColor-emphasis":
    "var(----display-auburn-borderColor-emphasis)",
  "--display-auburn-borderColor-muted":
    "var(----display-auburn-borderColor-muted)",
  "--display-auburn-fgColor": "var(----display-auburn-fgColor)",
  "--display-auburn-scale-0": "var(----display-auburn-scale-0)",
  "--display-auburn-scale-1": "var(----display-auburn-scale-1)",
  "--display-auburn-scale-2": "var(----display-auburn-scale-2)",
  "--display-auburn-scale-3": "var(----display-auburn-scale-3)",
  "--display-auburn-scale-4": "var(----display-auburn-scale-4)",
  "--display-auburn-scale-5": "var(----display-auburn-scale-5)",
  "--display-auburn-scale-6": "var(----display-auburn-scale-6)",
  "--display-auburn-scale-7": "var(----display-auburn-scale-7)",
  "--display-auburn-scale-8": "var(----display-auburn-scale-8)",
  "--display-auburn-scale-9": "var(----display-auburn-scale-9)",
  "--display-blue-bgColor-emphasis": "var(----display-blue-bgColor-emphasis)",
  "--display-blue-bgColor-muted": "var(----display-blue-bgColor-muted)",
  "--display-blue-borderColor-emphasis":
    "var(----display-blue-borderColor-emphasis)",
  "--display-blue-borderColor-muted": "var(----display-blue-borderColor-muted)",
  "--display-blue-fgColor": "var(----display-blue-fgColor)",
  "--display-blue-scale-0": "var(----display-blue-scale-0)",
  "--display-blue-scale-1": "var(----display-blue-scale-1)",
  "--display-blue-scale-2": "var(----display-blue-scale-2)",
  "--display-blue-scale-3": "var(----display-blue-scale-3)",
  "--display-blue-scale-4": "var(----display-blue-scale-4)",
  "--display-blue-scale-5": "var(----display-blue-scale-5)",
  "--display-blue-scale-6": "var(----display-blue-scale-6)",
  "--display-blue-scale-7": "var(----display-blue-scale-7)",
  "--display-blue-scale-8": "var(----display-blue-scale-8)",
  "--display-blue-scale-9": "var(----display-blue-scale-9)",
  "--display-brown-bgColor-emphasis": "var(----display-brown-bgColor-emphasis)",
  "--display-brown-bgColor-muted": "var(----display-brown-bgColor-muted)",
  "--display-brown-borderColor-emphasis":
    "var(----display-brown-borderColor-emphasis)",
  "--display-brown-borderColor-muted":
    "var(----display-brown-borderColor-muted)",
  "--display-brown-fgColor": "var(----display-brown-fgColor)",
  "--display-brown-scale-0": "var(----display-brown-scale-0)",
  "--display-brown-scale-1": "var(----display-brown-scale-1)",
  "--display-brown-scale-2": "var(----display-brown-scale-2)",
  "--display-brown-scale-3": "var(----display-brown-scale-3)",
  "--display-brown-scale-4": "var(----display-brown-scale-4)",
  "--display-brown-scale-5": "var(----display-brown-scale-5)",
  "--display-brown-scale-6": "var(----display-brown-scale-6)",
  "--display-brown-scale-7": "var(----display-brown-scale-7)",
  "--display-brown-scale-8": "var(----display-brown-scale-8)",
  "--display-brown-scale-9": "var(----display-brown-scale-9)",
  "--display-coral-bgColor-emphasis": "var(----display-coral-bgColor-emphasis)",
  "--display-coral-bgColor-muted": "var(----display-coral-bgColor-muted)",
  "--display-coral-borderColor-emphasis":
    "var(----display-coral-borderColor-emphasis)",
  "--display-coral-borderColor-muted":
    "var(----display-coral-borderColor-muted)",
  "--display-coral-fgColor": "var(----display-coral-fgColor)",
  "--display-coral-scale-0": "var(----display-coral-scale-0)",
  "--display-coral-scale-1": "var(----display-coral-scale-1)",
  "--display-coral-scale-2": "var(----display-coral-scale-2)",
  "--display-coral-scale-3": "var(----display-coral-scale-3)",
  "--display-coral-scale-4": "var(----display-coral-scale-4)",
  "--display-coral-scale-5": "var(----display-coral-scale-5)",
  "--display-coral-scale-6": "var(----display-coral-scale-6)",
  "--display-coral-scale-7": "var(----display-coral-scale-7)",
  "--display-coral-scale-8": "var(----display-coral-scale-8)",
  "--display-coral-scale-9": "var(----display-coral-scale-9)",
  "--display-cyan-bgColor-emphasis": "var(----display-cyan-bgColor-emphasis)",
  "--display-cyan-bgColor-muted": "var(----display-cyan-bgColor-muted)",
  "--display-cyan-borderColor-emphasis":
    "var(----display-cyan-borderColor-emphasis)",
  "--display-cyan-borderColor-muted": "var(----display-cyan-borderColor-muted)",
  "--display-cyan-fgColor": "var(----display-cyan-fgColor)",
  "--display-cyan-scale-0": "var(----display-cyan-scale-0)",
  "--display-cyan-scale-1": "var(----display-cyan-scale-1)",
  "--display-cyan-scale-2": "var(----display-cyan-scale-2)",
  "--display-cyan-scale-3": "var(----display-cyan-scale-3)",
  "--display-cyan-scale-4": "var(----display-cyan-scale-4)",
  "--display-cyan-scale-5": "var(----display-cyan-scale-5)",
  "--display-cyan-scale-6": "var(----display-cyan-scale-6)",
  "--display-cyan-scale-7": "var(----display-cyan-scale-7)",
  "--display-cyan-scale-8": "var(----display-cyan-scale-8)",
  "--display-cyan-scale-9": "var(----display-cyan-scale-9)",
  "--display-gray-bgColor-emphasis": "var(----display-gray-bgColor-emphasis)",
  "--display-gray-bgColor-muted": "var(----display-gray-bgColor-muted)",
  "--display-gray-borderColor-emphasis":
    "var(----display-gray-borderColor-emphasis)",
  "--display-gray-borderColor-muted": "var(----display-gray-borderColor-muted)",
  "--display-gray-fgColor": "var(----display-gray-fgColor)",
  "--display-gray-scale-0": "var(----display-gray-scale-0)",
  "--display-gray-scale-1": "var(----display-gray-scale-1)",
  "--display-gray-scale-2": "var(----display-gray-scale-2)",
  "--display-gray-scale-3": "var(----display-gray-scale-3)",
  "--display-gray-scale-4": "var(----display-gray-scale-4)",
  "--display-gray-scale-5": "var(----display-gray-scale-5)",
  "--display-gray-scale-6": "var(----display-gray-scale-6)",
  "--display-gray-scale-7": "var(----display-gray-scale-7)",
  "--display-gray-scale-8": "var(----display-gray-scale-8)",
  "--display-gray-scale-9": "var(----display-gray-scale-9)",
  "--display-green-bgColor-emphasis": "var(----display-green-bgColor-emphasis)",
  "--display-green-bgColor-muted": "var(----display-green-bgColor-muted)",
  "--display-green-borderColor-emphasis":
    "var(----display-green-borderColor-emphasis)",
  "--display-green-borderColor-muted":
    "var(----display-green-borderColor-muted)",
  "--display-green-fgColor": "var(----display-green-fgColor)",
  "--display-green-scale-0": "var(----display-green-scale-0)",
  "--display-green-scale-1": "var(----display-green-scale-1)",
  "--display-green-scale-2": "var(----display-green-scale-2)",
  "--display-green-scale-3": "var(----display-green-scale-3)",
  "--display-green-scale-4": "var(----display-green-scale-4)",
  "--display-green-scale-5": "var(----display-green-scale-5)",
  "--display-green-scale-6": "var(----display-green-scale-6)",
  "--display-green-scale-7": "var(----display-green-scale-7)",
  "--display-green-scale-8": "var(----display-green-scale-8)",
  "--display-green-scale-9": "var(----display-green-scale-9)",
  "--display-indigo-bgColor-emphasis":
    "var(----display-indigo-bgColor-emphasis)",
  "--display-indigo-bgColor-muted": "var(----display-indigo-bgColor-muted)",
  "--display-indigo-borderColor-emphasis":
    "var(----display-indigo-borderColor-emphasis)",
  "--display-indigo-borderColor-muted":
    "var(----display-indigo-borderColor-muted)",
  "--display-indigo-fgColor": "var(----display-indigo-fgColor)",
  "--display-indigo-scale-0": "var(----display-indigo-scale-0)",
  "--display-indigo-scale-1": "var(----display-indigo-scale-1)",
  "--display-indigo-scale-2": "var(----display-indigo-scale-2)",
  "--display-indigo-scale-3": "var(----display-indigo-scale-3)",
  "--display-indigo-scale-4": "var(----display-indigo-scale-4)",
  "--display-indigo-scale-5": "var(----display-indigo-scale-5)",
  "--display-indigo-scale-6": "var(----display-indigo-scale-6)",
  "--display-indigo-scale-7": "var(----display-indigo-scale-7)",
  "--display-indigo-scale-8": "var(----display-indigo-scale-8)",
  "--display-indigo-scale-9": "var(----display-indigo-scale-9)",
  "--display-lemon-bgColor-emphasis": "var(----display-lemon-bgColor-emphasis)",
  "--display-lemon-bgColor-muted": "var(----display-lemon-bgColor-muted)",
  "--display-lemon-borderColor-emphasis":
    "var(----display-lemon-borderColor-emphasis)",
  "--display-lemon-borderColor-muted":
    "var(----display-lemon-borderColor-muted)",
  "--display-lemon-fgColor": "var(----display-lemon-fgColor)",
  "--display-lemon-scale-0": "var(----display-lemon-scale-0)",
  "--display-lemon-scale-1": "var(----display-lemon-scale-1)",
  "--display-lemon-scale-2": "var(----display-lemon-scale-2)",
  "--display-lemon-scale-3": "var(----display-lemon-scale-3)",
  "--display-lemon-scale-4": "var(----display-lemon-scale-4)",
  "--display-lemon-scale-5": "var(----display-lemon-scale-5)",
  "--display-lemon-scale-6": "var(----display-lemon-scale-6)",
  "--display-lemon-scale-7": "var(----display-lemon-scale-7)",
  "--display-lemon-scale-8": "var(----display-lemon-scale-8)",
  "--display-lemon-scale-9": "var(----display-lemon-scale-9)",
  "--display-lime-bgColor-emphasis": "var(----display-lime-bgColor-emphasis)",
  "--display-lime-bgColor-muted": "var(----display-lime-bgColor-muted)",
  "--display-lime-borderColor-emphasis":
    "var(----display-lime-borderColor-emphasis)",
  "--display-lime-borderColor-muted": "var(----display-lime-borderColor-muted)",
  "--display-lime-fgColor": "var(----display-lime-fgColor)",
  "--display-lime-scale-0": "var(----display-lime-scale-0)",
  "--display-lime-scale-1": "var(----display-lime-scale-1)",
  "--display-lime-scale-2": "var(----display-lime-scale-2)",
  "--display-lime-scale-3": "var(----display-lime-scale-3)",
  "--display-lime-scale-4": "var(----display-lime-scale-4)",
  "--display-lime-scale-5": "var(----display-lime-scale-5)",
  "--display-lime-scale-6": "var(----display-lime-scale-6)",
  "--display-lime-scale-7": "var(----display-lime-scale-7)",
  "--display-lime-scale-8": "var(----display-lime-scale-8)",
  "--display-lime-scale-9": "var(----display-lime-scale-9)",
  "--display-olive-bgColor-emphasis": "var(----display-olive-bgColor-emphasis)",
  "--display-olive-bgColor-muted": "var(----display-olive-bgColor-muted)",
  "--display-olive-borderColor-emphasis":
    "var(----display-olive-borderColor-emphasis)",
  "--display-olive-borderColor-muted":
    "var(----display-olive-borderColor-muted)",
  "--display-olive-fgColor": "var(----display-olive-fgColor)",
  "--display-olive-scale-0": "var(----display-olive-scale-0)",
  "--display-olive-scale-1": "var(----display-olive-scale-1)",
  "--display-olive-scale-2": "var(----display-olive-scale-2)",
  "--display-olive-scale-3": "var(----display-olive-scale-3)",
  "--display-olive-scale-4": "var(----display-olive-scale-4)",
  "--display-olive-scale-5": "var(----display-olive-scale-5)",
  "--display-olive-scale-6": "var(----display-olive-scale-6)",
  "--display-olive-scale-7": "var(----display-olive-scale-7)",
  "--display-olive-scale-8": "var(----display-olive-scale-8)",
  "--display-olive-scale-9": "var(----display-olive-scale-9)",
  "--display-orange-bgColor-emphasis":
    "var(----display-orange-bgColor-emphasis)",
  "--display-orange-bgColor-muted": "var(----display-orange-bgColor-muted)",
  "--display-orange-borderColor-emphasis":
    "var(----display-orange-borderColor-emphasis)",
  "--display-orange-borderColor-muted":
    "var(----display-orange-borderColor-muted)",
  "--display-orange-fgColor": "var(----display-orange-fgColor)",
  "--display-orange-scale-0": "var(----display-orange-scale-0)",
  "--display-orange-scale-1": "var(----display-orange-scale-1)",
  "--display-orange-scale-2": "var(----display-orange-scale-2)",
  "--display-orange-scale-3": "var(----display-orange-scale-3)",
  "--display-orange-scale-4": "var(----display-orange-scale-4)",
  "--display-orange-scale-5": "var(----display-orange-scale-5)",
  "--display-orange-scale-6": "var(----display-orange-scale-6)",
  "--display-orange-scale-7": "var(----display-orange-scale-7)",
  "--display-orange-scale-8": "var(----display-orange-scale-8)",
  "--display-orange-scale-9": "var(----display-orange-scale-9)",
  "--display-pine-bgColor-emphasis": "var(----display-pine-bgColor-emphasis)",
  "--display-pine-bgColor-muted": "var(----display-pine-bgColor-muted)",
  "--display-pine-borderColor-emphasis":
    "var(----display-pine-borderColor-emphasis)",
  "--display-pine-borderColor-muted": "var(----display-pine-borderColor-muted)",
  "--display-pine-fgColor": "var(----display-pine-fgColor)",
  "--display-pine-scale-0": "var(----display-pine-scale-0)",
  "--display-pine-scale-1": "var(----display-pine-scale-1)",
  "--display-pine-scale-2": "var(----display-pine-scale-2)",
  "--display-pine-scale-3": "var(----display-pine-scale-3)",
  "--display-pine-scale-4": "var(----display-pine-scale-4)",
  "--display-pine-scale-5": "var(----display-pine-scale-5)",
  "--display-pine-scale-6": "var(----display-pine-scale-6)",
  "--display-pine-scale-7": "var(----display-pine-scale-7)",
  "--display-pine-scale-8": "var(----display-pine-scale-8)",
  "--display-pine-scale-9": "var(----display-pine-scale-9)",
  "--display-pink-bgColor-emphasis": "var(----display-pink-bgColor-emphasis)",
  "--display-pink-bgColor-muted": "var(----display-pink-bgColor-muted)",
  "--display-pink-borderColor-emphasis":
    "var(----display-pink-borderColor-emphasis)",
  "--display-pink-borderColor-muted": "var(----display-pink-borderColor-muted)",
  "--display-pink-fgColor": "var(----display-pink-fgColor)",
  "--display-pink-scale-0": "var(----display-pink-scale-0)",
  "--display-pink-scale-1": "var(----display-pink-scale-1)",
  "--display-pink-scale-2": "var(----display-pink-scale-2)",
  "--display-pink-scale-3": "var(----display-pink-scale-3)",
  "--display-pink-scale-4": "var(----display-pink-scale-4)",
  "--display-pink-scale-5": "var(----display-pink-scale-5)",
  "--display-pink-scale-6": "var(----display-pink-scale-6)",
  "--display-pink-scale-7": "var(----display-pink-scale-7)",
  "--display-pink-scale-8": "var(----display-pink-scale-8)",
  "--display-pink-scale-9": "var(----display-pink-scale-9)",
  "--display-plum-bgColor-emphasis": "var(----display-plum-bgColor-emphasis)",
  "--display-plum-bgColor-muted": "var(----display-plum-bgColor-muted)",
  "--display-plum-borderColor-emphasis":
    "var(----display-plum-borderColor-emphasis)",
  "--display-plum-borderColor-muted": "var(----display-plum-borderColor-muted)",
  "--display-plum-fgColor": "var(----display-plum-fgColor)",
  "--display-plum-scale-0": "var(----display-plum-scale-0)",
  "--display-plum-scale-1": "var(----display-plum-scale-1)",
  "--display-plum-scale-2": "var(----display-plum-scale-2)",
  "--display-plum-scale-3": "var(----display-plum-scale-3)",
  "--display-plum-scale-4": "var(----display-plum-scale-4)",
  "--display-plum-scale-5": "var(----display-plum-scale-5)",
  "--display-plum-scale-6": "var(----display-plum-scale-6)",
  "--display-plum-scale-7": "var(----display-plum-scale-7)",
  "--display-plum-scale-8": "var(----display-plum-scale-8)",
  "--display-plum-scale-9": "var(----display-plum-scale-9)",
  "--display-purple-bgColor-emphasis":
    "var(----display-purple-bgColor-emphasis)",
  "--display-purple-bgColor-muted": "var(----display-purple-bgColor-muted)",
  "--display-purple-borderColor-emphasis":
    "var(----display-purple-borderColor-emphasis)",
  "--display-purple-borderColor-muted":
    "var(----display-purple-borderColor-muted)",
  "--display-purple-fgColor": "var(----display-purple-fgColor)",
  "--display-purple-scale-0": "var(----display-purple-scale-0)",
  "--display-purple-scale-1": "var(----display-purple-scale-1)",
  "--display-purple-scale-2": "var(----display-purple-scale-2)",
  "--display-purple-scale-3": "var(----display-purple-scale-3)",
  "--display-purple-scale-4": "var(----display-purple-scale-4)",
  "--display-purple-scale-5": "var(----display-purple-scale-5)",
  "--display-purple-scale-6": "var(----display-purple-scale-6)",
  "--display-purple-scale-7": "var(----display-purple-scale-7)",
  "--display-purple-scale-8": "var(----display-purple-scale-8)",
  "--display-purple-scale-9": "var(----display-purple-scale-9)",
  "--display-red-bgColor-emphasis": "var(----display-red-bgColor-emphasis)",
  "--display-red-bgColor-muted": "var(----display-red-bgColor-muted)",
  "--display-red-borderColor-emphasis":
    "var(----display-red-borderColor-emphasis)",
  "--display-red-borderColor-muted": "var(----display-red-borderColor-muted)",
  "--display-red-fgColor": "var(----display-red-fgColor)",
  "--display-red-scale-0": "var(----display-red-scale-0)",
  "--display-red-scale-1": "var(----display-red-scale-1)",
  "--display-red-scale-2": "var(----display-red-scale-2)",
  "--display-red-scale-3": "var(----display-red-scale-3)",
  "--display-red-scale-4": "var(----display-red-scale-4)",
  "--display-red-scale-5": "var(----display-red-scale-5)",
  "--display-red-scale-6": "var(----display-red-scale-6)",
  "--display-red-scale-7": "var(----display-red-scale-7)",
  "--display-red-scale-8": "var(----display-red-scale-8)",
  "--display-red-scale-9": "var(----display-red-scale-9)",
  "--display-teal-bgColor-emphasis": "var(----display-teal-bgColor-emphasis)",
  "--display-teal-bgColor-muted": "var(----display-teal-bgColor-muted)",
  "--display-teal-borderColor-emphasis":
    "var(----display-teal-borderColor-emphasis)",
  "--display-teal-borderColor-muted": "var(----display-teal-borderColor-muted)",
  "--display-teal-fgColor": "var(----display-teal-fgColor)",
  "--display-teal-scale-0": "var(----display-teal-scale-0)",
  "--display-teal-scale-1": "var(----display-teal-scale-1)",
  "--display-teal-scale-2": "var(----display-teal-scale-2)",
  "--display-teal-scale-3": "var(----display-teal-scale-3)",
  "--display-teal-scale-4": "var(----display-teal-scale-4)",
  "--display-teal-scale-5": "var(----display-teal-scale-5)",
  "--display-teal-scale-6": "var(----display-teal-scale-6)",
  "--display-teal-scale-7": "var(----display-teal-scale-7)",
  "--display-teal-scale-8": "var(----display-teal-scale-8)",
  "--display-teal-scale-9": "var(----display-teal-scale-9)",
  "--display-yellow-bgColor-emphasis":
    "var(----display-yellow-bgColor-emphasis)",
  "--display-yellow-bgColor-muted": "var(----display-yellow-bgColor-muted)",
  "--display-yellow-borderColor-emphasis":
    "var(----display-yellow-borderColor-emphasis)",
  "--display-yellow-borderColor-muted":
    "var(----display-yellow-borderColor-muted)",
  "--display-yellow-fgColor": "var(----display-yellow-fgColor)",
  "--display-yellow-scale-0": "var(----display-yellow-scale-0)",
  "--display-yellow-scale-1": "var(----display-yellow-scale-1)",
  "--display-yellow-scale-2": "var(----display-yellow-scale-2)",
  "--display-yellow-scale-3": "var(----display-yellow-scale-3)",
  "--display-yellow-scale-4": "var(----display-yellow-scale-4)",
  "--display-yellow-scale-5": "var(----display-yellow-scale-5)",
  "--display-yellow-scale-6": "var(----display-yellow-scale-6)",
  "--display-yellow-scale-7": "var(----display-yellow-scale-7)",
  "--display-yellow-scale-8": "var(----display-yellow-scale-8)",
  "--display-yellow-scale-9": "var(----display-yellow-scale-9)",
  "--fgColor-attention": "var(----fgColor-attention)",
  "--fgColor-danger": "var(----fgColor-danger)",
  "--fgColor-default": "var(----fgColor-default)",
  "--fgColor-disabled": "var(----fgColor-disabled)",
  "--fgColor-done": "var(----fgColor-done)",
  "--fgColor-link": "var(----fgColor-link)",
  "--fgColor-muted": "var(----fgColor-muted)",
  "--fgColor-neutral": "var(----fgColor-neutral)",
  "--fgColor-severe": "var(----fgColor-severe)",
  "--fgColor-sponsors": "var(----fgColor-sponsors)",
  "--fgColor-success": "var(----fgColor-success)",
  "--header-bgColor": "var(----header-bgColor)",
  "--header-borderColor-divider": "var(----header-borderColor-divider)",
  "--header-fgColor-logo": "var(----header-fgColor-logo)",
  "--headerSearch-bgColor": "var(----headerSearch-bgColor)",
  "--headerSearch-borderColor": "var(----headerSearch-borderColor)",
  "--highlight-neutral-bgColor": "var(----highlight-neutral-bgColor)",
  "--label-auburn-bgColor-active": "var(----label-auburn-bgColor-active)",
  "--label-auburn-bgColor-hover": "var(----label-auburn-bgColor-hover)",
  "--label-auburn-bgColor-rest": "var(----label-auburn-bgColor-rest)",
  "--label-auburn-borderColor": "var(----label-auburn-borderColor)",
  "--label-auburn-fgColor-active": "var(----label-auburn-fgColor-active)",
  "--label-auburn-fgColor-hover": "var(----label-auburn-fgColor-hover)",
  "--label-auburn-fgColor-rest": "var(----label-auburn-fgColor-rest)",
  "--label-blue-bgColor-active": "var(----label-blue-bgColor-active)",
  "--label-blue-bgColor-hover": "var(----label-blue-bgColor-hover)",
  "--label-blue-bgColor-rest": "var(----label-blue-bgColor-rest)",
  "--label-blue-borderColor": "var(----label-blue-borderColor)",
  "--label-blue-fgColor-active": "var(----label-blue-fgColor-active)",
  "--label-blue-fgColor-hover": "var(----label-blue-fgColor-hover)",
  "--label-blue-fgColor-rest": "var(----label-blue-fgColor-rest)",
  "--label-brown-bgColor-active": "var(----label-brown-bgColor-active)",
  "--label-brown-bgColor-hover": "var(----label-brown-bgColor-hover)",
  "--label-brown-bgColor-rest": "var(----label-brown-bgColor-rest)",
  "--label-brown-borderColor": "var(----label-brown-borderColor)",
  "--label-brown-fgColor-active": "var(----label-brown-fgColor-active)",
  "--label-brown-fgColor-hover": "var(----label-brown-fgColor-hover)",
  "--label-brown-fgColor-rest": "var(----label-brown-fgColor-rest)",
  "--label-coral-bgColor-active": "var(----label-coral-bgColor-active)",
  "--label-coral-bgColor-hover": "var(----label-coral-bgColor-hover)",
  "--label-coral-bgColor-rest": "var(----label-coral-bgColor-rest)",
  "--label-coral-borderColor": "var(----label-coral-borderColor)",
  "--label-coral-fgColor-active": "var(----label-coral-fgColor-active)",
  "--label-coral-fgColor-hover": "var(----label-coral-fgColor-hover)",
  "--label-coral-fgColor-rest": "var(----label-coral-fgColor-rest)",
  "--label-cyan-bgColor-active": "var(----label-cyan-bgColor-active)",
  "--label-cyan-bgColor-hover": "var(----label-cyan-bgColor-hover)",
  "--label-cyan-bgColor-rest": "var(----label-cyan-bgColor-rest)",
  "--label-cyan-borderColor": "var(----label-cyan-borderColor)",
  "--label-cyan-fgColor-active": "var(----label-cyan-fgColor-active)",
  "--label-cyan-fgColor-hover": "var(----label-cyan-fgColor-hover)",
  "--label-cyan-fgColor-rest": "var(----label-cyan-fgColor-rest)",
  "--label-gray-bgColor-active": "var(----label-gray-bgColor-active)",
  "--label-gray-bgColor-hover": "var(----label-gray-bgColor-hover)",
  "--label-gray-bgColor-rest": "var(----label-gray-bgColor-rest)",
  "--label-gray-borderColor": "var(----label-gray-borderColor)",
  "--label-gray-fgColor-active": "var(----label-gray-fgColor-active)",
  "--label-gray-fgColor-hover": "var(----label-gray-fgColor-hover)",
  "--label-gray-fgColor-rest": "var(----label-gray-fgColor-rest)",
  "--label-green-bgColor-active": "var(----label-green-bgColor-active)",
  "--label-green-bgColor-hover": "var(----label-green-bgColor-hover)",
  "--label-green-bgColor-rest": "var(----label-green-bgColor-rest)",
  "--label-green-borderColor": "var(----label-green-borderColor)",
  "--label-green-fgColor-active": "var(----label-green-fgColor-active)",
  "--label-green-fgColor-hover": "var(----label-green-fgColor-hover)",
  "--label-green-fgColor-rest": "var(----label-green-fgColor-rest)",
  "--label-indigo-bgColor-active": "var(----label-indigo-bgColor-active)",
  "--label-indigo-bgColor-hover": "var(----label-indigo-bgColor-hover)",
  "--label-indigo-bgColor-rest": "var(----label-indigo-bgColor-rest)",
  "--label-indigo-borderColor": "var(----label-indigo-borderColor)",
  "--label-indigo-fgColor-active": "var(----label-indigo-fgColor-active)",
  "--label-indigo-fgColor-hover": "var(----label-indigo-fgColor-hover)",
  "--label-indigo-fgColor-rest": "var(----label-indigo-fgColor-rest)",
  "--label-lemon-bgColor-active": "var(----label-lemon-bgColor-active)",
  "--label-lemon-bgColor-hover": "var(----label-lemon-bgColor-hover)",
  "--label-lemon-bgColor-rest": "var(----label-lemon-bgColor-rest)",
  "--label-lemon-borderColor": "var(----label-lemon-borderColor)",
  "--label-lemon-fgColor-active": "var(----label-lemon-fgColor-active)",
  "--label-lemon-fgColor-hover": "var(----label-lemon-fgColor-hover)",
  "--label-lemon-fgColor-rest": "var(----label-lemon-fgColor-rest)",
  "--label-lime-bgColor-active": "var(----label-lime-bgColor-active)",
  "--label-lime-bgColor-hover": "var(----label-lime-bgColor-hover)",
  "--label-lime-bgColor-rest": "var(----label-lime-bgColor-rest)",
  "--label-lime-borderColor": "var(----label-lime-borderColor)",
  "--label-lime-fgColor-active": "var(----label-lime-fgColor-active)",
  "--label-lime-fgColor-hover": "var(----label-lime-fgColor-hover)",
  "--label-lime-fgColor-rest": "var(----label-lime-fgColor-rest)",
  "--label-olive-bgColor-active": "var(----label-olive-bgColor-active)",
  "--label-olive-bgColor-hover": "var(----label-olive-bgColor-hover)",
  "--label-olive-bgColor-rest": "var(----label-olive-bgColor-rest)",
  "--label-olive-borderColor": "var(----label-olive-borderColor)",
  "--label-olive-fgColor-active": "var(----label-olive-fgColor-active)",
  "--label-olive-fgColor-hover": "var(----label-olive-fgColor-hover)",
  "--label-olive-fgColor-rest": "var(----label-olive-fgColor-rest)",
  "--label-orange-bgColor-active": "var(----label-orange-bgColor-active)",
  "--label-orange-bgColor-hover": "var(----label-orange-bgColor-hover)",
  "--label-orange-bgColor-rest": "var(----label-orange-bgColor-rest)",
  "--label-orange-borderColor": "var(----label-orange-borderColor)",
  "--label-orange-fgColor-active": "var(----label-orange-fgColor-active)",
  "--label-orange-fgColor-hover": "var(----label-orange-fgColor-hover)",
  "--label-orange-fgColor-rest": "var(----label-orange-fgColor-rest)",
  "--label-pine-bgColor-active": "var(----label-pine-bgColor-active)",
  "--label-pine-bgColor-hover": "var(----label-pine-bgColor-hover)",
  "--label-pine-bgColor-rest": "var(----label-pine-bgColor-rest)",
  "--label-pine-borderColor": "var(----label-pine-borderColor)",
  "--label-pine-fgColor-active": "var(----label-pine-fgColor-active)",
  "--label-pine-fgColor-hover": "var(----label-pine-fgColor-hover)",
  "--label-pine-fgColor-rest": "var(----label-pine-fgColor-rest)",
  "--label-pink-bgColor-active": "var(----label-pink-bgColor-active)",
  "--label-pink-bgColor-hover": "var(----label-pink-bgColor-hover)",
  "--label-pink-bgColor-rest": "var(----label-pink-bgColor-rest)",
  "--label-pink-borderColor": "var(----label-pink-borderColor)",
  "--label-pink-fgColor-active": "var(----label-pink-fgColor-active)",
  "--label-pink-fgColor-hover": "var(----label-pink-fgColor-hover)",
  "--label-pink-fgColor-rest": "var(----label-pink-fgColor-rest)",
  "--label-plum-bgColor-active": "var(----label-plum-bgColor-active)",
  "--label-plum-bgColor-hover": "var(----label-plum-bgColor-hover)",
  "--label-plum-bgColor-rest": "var(----label-plum-bgColor-rest)",
  "--label-plum-borderColor": "var(----label-plum-borderColor)",
  "--label-plum-fgColor-active": "var(----label-plum-fgColor-active)",
  "--label-plum-fgColor-hover": "var(----label-plum-fgColor-hover)",
  "--label-plum-fgColor-rest": "var(----label-plum-fgColor-rest)",
  "--label-purple-bgColor-active": "var(----label-purple-bgColor-active)",
  "--label-purple-bgColor-hover": "var(----label-purple-bgColor-hover)",
  "--label-purple-bgColor-rest": "var(----label-purple-bgColor-rest)",
  "--label-purple-borderColor": "var(----label-purple-borderColor)",
  "--label-purple-fgColor-active": "var(----label-purple-fgColor-active)",
  "--label-purple-fgColor-hover": "var(----label-purple-fgColor-hover)",
  "--label-purple-fgColor-rest": "var(----label-purple-fgColor-rest)",
  "--label-red-bgColor-active": "var(----label-red-bgColor-active)",
  "--label-red-bgColor-hover": "var(----label-red-bgColor-hover)",
  "--label-red-bgColor-rest": "var(----label-red-bgColor-rest)",
  "--label-red-borderColor": "var(----label-red-borderColor)",
  "--label-red-fgColor-active": "var(----label-red-fgColor-active)",
  "--label-red-fgColor-hover": "var(----label-red-fgColor-hover)",
  "--label-red-fgColor-rest": "var(----label-red-fgColor-rest)",
  "--label-teal-bgColor-active": "var(----label-teal-bgColor-active)",
  "--label-teal-bgColor-hover": "var(----label-teal-bgColor-hover)",
  "--label-teal-bgColor-rest": "var(----label-teal-bgColor-rest)",
  "--label-teal-borderColor": "var(----label-teal-borderColor)",
  "--label-teal-fgColor-active": "var(----label-teal-fgColor-active)",
  "--label-teal-fgColor-hover": "var(----label-teal-fgColor-hover)",
  "--label-teal-fgColor-rest": "var(----label-teal-fgColor-rest)",
  "--label-yellow-bgColor-active": "var(----label-yellow-bgColor-active)",
  "--label-yellow-bgColor-hover": "var(----label-yellow-bgColor-hover)",
  "--label-yellow-bgColor-rest": "var(----label-yellow-bgColor-rest)",
  "--label-yellow-borderColor": "var(----label-yellow-borderColor)",
  "--label-yellow-fgColor-active": "var(----label-yellow-fgColor-active)",
  "--label-yellow-fgColor-hover": "var(----label-yellow-fgColor-hover)",
  "--label-yellow-fgColor-rest": "var(----label-yellow-fgColor-rest)",
  "--menu-bgColor-active": "var(----menu-bgColor-active)",
  "--overlay-backdrop-bgColor": "var(----overlay-backdrop-bgColor)",
  "--progressBar-track-borderColor": "var(----progressBar-track-borderColor)",
  "--reactionButton-selected-bgColor-rest":
    "var(----reactionButton-selected-bgColor-rest)",
  "--reactionButton-selected-fgColor-hover":
    "var(----reactionButton-selected-fgColor-hover)",
  "--selectMenu-bgColor-active": "var(----selectMenu-bgColor-active)",
  "--sideNav-bgColor-selected": "var(----sideNav-bgColor-selected)",
  "--skeletonLoader-bgColor": "var(----skeletonLoader-bgColor)",
  "--timelineBadge-bgColor": "var(----timelineBadge-bgColor)",
  "--topicTag-borderColor": "var(----topicTag-borderColor)",
  "--underlineNav-borderColor-active":
    "var(----underlineNav-borderColor-active)",
  "--avatar-bgColor": "var(----avatar-bgColor)",
  "--bgColor-black": "var(----bgColor-black)",
  "--bgColor-closed-emphasis": "var(----bgColor-closed-emphasis)",
  "--bgColor-closed-muted": "var(----bgColor-closed-muted)",
  "--bgColor-inset": "var(----bgColor-inset)",
  "--bgColor-inverse": "var(----bgColor-inverse)",
  "--bgColor-open-emphasis": "var(----bgColor-open-emphasis)",
  "--bgColor-open-muted": "var(----bgColor-open-muted)",
  "--bgColor-upsell-emphasis": "var(----bgColor-upsell-emphasis)",
  "--bgColor-upsell-muted": "var(----bgColor-upsell-muted)",
  "--bgColor-white": "var(----bgColor-white)",
  "--border-accent-emphasis": "var(----border-accent-emphasis)",
  "--border-accent-muted": "var(----border-accent-muted)",
  "--border-attention-emphasis": "var(----border-attention-emphasis)",
  "--border-attention-muted": "var(----border-attention-muted)",
  "--border-danger-emphasis": "var(----border-danger-emphasis)",
  "--border-danger-muted": "var(----border-danger-muted)",
  "--border-default": "var(----border-default)",
  "--border-disabled": "var(----border-disabled)",
  "--border-done-emphasis": "var(----border-done-emphasis)",
  "--border-done-muted": "var(----border-done-muted)",
  "--border-emphasis": "var(----border-emphasis)",
  "--border-severe-emphasis": "var(----border-severe-emphasis)",
  "--border-severe-muted": "var(----border-severe-muted)",
  "--border-sponsors-emphasis": "var(----border-sponsors-emphasis)",
  "--border-sponsors-muted": "var(----border-sponsors-muted)",
  "--border-success-emphasis": "var(----border-success-emphasis)",
  "--border-success-muted": "var(----border-success-muted)",
  "--border-transparent": "var(----border-transparent)",
  "--borderColor-closed-emphasis": "var(----borderColor-closed-emphasis)",
  "--borderColor-closed-muted": "var(----borderColor-closed-muted)",
  "--borderColor-muted": "var(----borderColor-muted)",
  "--borderColor-neutral-emphasis": "var(----borderColor-neutral-emphasis)",
  "--borderColor-open-emphasis": "var(----borderColor-open-emphasis)",
  "--borderColor-open-muted": "var(----borderColor-open-muted)",
  "--borderColor-translucent": "var(----borderColor-translucent)",
  "--borderColor-upsell-emphasis": "var(----borderColor-upsell-emphasis)",
  "--borderColor-upsell-muted": "var(----borderColor-upsell-muted)",
  "--button-danger-bgColor-active": "var(----button-danger-bgColor-active)",
  "--button-danger-bgColor-rest": "var(----button-danger-bgColor-rest)",
  "--button-danger-fgColor-active": "var(----button-danger-fgColor-active)",
  "--button-danger-fgColor-disabled": "var(----button-danger-fgColor-disabled)",
  "--button-danger-fgColor-hover": "var(----button-danger-fgColor-hover)",
  "--button-danger-iconColor-hover": "var(----button-danger-iconColor-hover)",
  "--button-default-bgColor-active": "var(----button-default-bgColor-active)",
  "--button-default-bgColor-hover": "var(----button-default-bgColor-hover)",
  "--button-default-bgColor-rest": "var(----button-default-bgColor-rest)",
  "--button-default-bgColor-selected":
    "var(----button-default-bgColor-selected)",
  "--button-invisible-bgColor-active":
    "var(----button-invisible-bgColor-active)",
  "--button-invisible-bgColor-hover": "var(----button-invisible-bgColor-hover)",
  "--button-invisible-bgColor-rest": "var(----button-invisible-bgColor-rest)",
  "--button-invisible-borderColor-hover":
    "var(----button-invisible-borderColor-hover)",
  "--button-invisible-borderColor-rest":
    "var(----button-invisible-borderColor-rest)",
  "--button-invisible-iconColor-hover":
    "var(----button-invisible-iconColor-hover)",
  "--button-invisible-iconColor-rest":
    "var(----button-invisible-iconColor-rest)",
  "--button-outline-bgColor-hover": "var(----button-outline-bgColor-hover)",
  "--button-outline-fgColor-active": "var(----button-outline-fgColor-active)",
  "--button-primary-bgColor-rest": "var(----button-primary-bgColor-rest)",
  "--button-primary-fgColor-disabled":
    "var(----button-primary-fgColor-disabled)",
  "--buttonCounter-danger-bgColor-disabled":
    "var(----buttonCounter-danger-bgColor-disabled)",
  "--buttonCounter-danger-bgColor-hover":
    "var(----buttonCounter-danger-bgColor-hover)",
  "--buttonCounter-danger-fgColor-disabled":
    "var(----buttonCounter-danger-fgColor-disabled)",
  "--buttonCounter-danger-fgColor-hover":
    "var(----buttonCounter-danger-fgColor-hover)",
  "--buttonCounter-danger-fgColor-rest":
    "var(----buttonCounter-danger-fgColor-rest)",
  "--buttonCounter-invisible-bgColor-rest":
    "var(----buttonCounter-invisible-bgColor-rest)",
  "--buttonCounter-outline-bgColor-disabled":
    "var(----buttonCounter-outline-bgColor-disabled)",
  "--card-bgColor": "var(----card-bgColor)",
  "--codeMirror-activeline-bgColor": "var(----codeMirror-activeline-bgColor)",
  "--codeMirror-bgColor": "var(----codeMirror-bgColor)",
  "--codeMirror-cursor-fgColor": "var(----codeMirror-cursor-fgColor)",
  "--codeMirror-fgColor": "var(----codeMirror-fgColor)",
  "--codeMirror-gutterMarker-fgColor-default":
    "var(----codeMirror-gutterMarker-fgColor-default)",
  "--codeMirror-gutterMarker-fgColor-muted":
    "var(----codeMirror-gutterMarker-fgColor-muted)",
  "--codeMirror-gutters-bgColor": "var(----codeMirror-gutters-bgColor)",
  "--codeMirror-lineNumber-fgColor": "var(----codeMirror-lineNumber-fgColor)",
  "--codeMirror-lines-bgColor": "var(----codeMirror-lines-bgColor)",
  "--codeMirror-matchingBracket-fgColor":
    "var(----codeMirror-matchingBracket-fgColor)",
  "--codeMirror-selection-bgColor": "var(----codeMirror-selection-bgColor)",
  "--color-ansi-white-bright": "var(----color-ansi-white-bright)",
  "--contribution-default-borderColor-1":
    "var(----contribution-default-borderColor-1)",
  "--contribution-default-borderColor-2":
    "var(----contribution-default-borderColor-2)",
  "--contribution-default-borderColor-3":
    "var(----contribution-default-borderColor-3)",
  "--contribution-default-borderColor-4":
    "var(----contribution-default-borderColor-4)",
  "--control-bgColor-disabled": "var(----control-bgColor-disabled)",
  "--control-bgColor-selected": "var(----control-bgColor-selected)",
  "--control-borderColor-danger": "var(----control-borderColor-danger)",
  "--control-borderColor-disabled": "var(----control-borderColor-disabled)",
  "--control-borderColor-emphasis": "var(----control-borderColor-emphasis)",
  "--control-borderColor-rest": "var(----control-borderColor-rest)",
  "--control-borderColor-success": "var(----control-borderColor-success)",
  "--control-borderColor-warning": "var(----control-borderColor-warning)",
  "--control-checked-bgColor-disabled":
    "var(----control-checked-bgColor-disabled)",
  "--control-checked-bgColor-rest": "var(----control-checked-bgColor-rest)",
  "--control-checked-fgColor-disabled":
    "var(----control-checked-fgColor-disabled)",
  "--control-danger-bgColor-active": "var(----control-danger-bgColor-active)",
  "--control-danger-bgColor-hover": "var(----control-danger-bgColor-hover)",
  "--control-danger-fgColor-rest": "var(----control-danger-fgColor-rest)",
  "--control-fgColor-disabled": "var(----control-fgColor-disabled)",
  "--control-fgColor-placeholder": "var(----control-fgColor-placeholder)",
  "--control-fgColor-rest": "var(----control-fgColor-rest)",
  "--control-iconColor-rest": "var(----control-iconColor-rest)",
  "--control-transparent-bgColor-disabled":
    "var(----control-transparent-bgColor-disabled)",
  "--controlKnob-bgColor-checked": "var(----controlKnob-bgColor-checked)",
  "--controlTrack-bgColor-disabled": "var(----controlTrack-bgColor-disabled)",
  "--controlTrack-borderColor-disabled":
    "var(----controlTrack-borderColor-disabled)",
  "--controlTrack-borderColor-rest": "var(----controlTrack-borderColor-rest)",
  "--controlTrack-fgColor-rest": "var(----controlTrack-fgColor-rest)",
  "--counter-bgColor-emphasis": "var(----counter-bgColor-emphasis)",
  "--counter-bgColor-muted": "var(----counter-bgColor-muted)",
  "--diffBlob-additionLine-bgColor": "var(----diffBlob-additionLine-bgColor)",
  "--diffBlob-additionLine-fgColor": "var(----diffBlob-additionLine-fgColor)",
  "--diffBlob-additionNum-fgColor": "var(----diffBlob-additionNum-fgColor)",
  "--diffBlob-additionWord-fgColor": "var(----diffBlob-additionWord-fgColor)",
  "--diffBlob-deletionLine-bgColor": "var(----diffBlob-deletionLine-bgColor)",
  "--diffBlob-deletionLine-fgColor": "var(----diffBlob-deletionLine-fgColor)",
  "--diffBlob-deletionNum-fgColor": "var(----diffBlob-deletionNum-fgColor)",
  "--diffBlob-deletionWord-fgColor": "var(----diffBlob-deletionWord-fgColor)",
  "--diffBlob-emptyLine-bgColor": "var(----diffBlob-emptyLine-bgColor)",
  "--diffBlob-emptyNum-bgColor": "var(----diffBlob-emptyNum-bgColor)",
  "--diffBlob-expander-iconColor": "var(----diffBlob-expander-iconColor)",
  "--diffBlob-hunkLine-bgColor": "var(----diffBlob-hunkLine-bgColor)",
  "--diffBlob-hunkLine-fgColor": "var(----diffBlob-hunkLine-fgColor)",
  "--diffBlob-hunkNum-bgColor-hover": "var(----diffBlob-hunkNum-bgColor-hover)",
  "--diffBlob-hunkNum-fgColor-rest": "var(----diffBlob-hunkNum-fgColor-rest)",
  "--fgColor-black": "var(----fgColor-black)",
  "--fgColor-closed": "var(----fgColor-closed)",
  "--fgColor-onEmphasis": "var(----fgColor-onEmphasis)",
  "--fgColor-onInverse": "var(----fgColor-onInverse)",
  "--fgColor-open": "var(----fgColor-open)",
  "--fgColor-upsell": "var(----fgColor-upsell)",
  "--fgColor-white": "var(----fgColor-white)",
  "--focus-outlineColor": "var(----focus-outlineColor)",
  "--header-fgColor-default": "var(----header-fgColor-default)",
  "--overlay-bgColor": "var(----overlay-bgColor)",
  "--page-header-bgColor": "var(----page-header-bgColor)",
  "--progressBar-bgColor-accent": "var(----progressBar-bgColor-accent)",
  "--progressBar-bgColor-attention": "var(----progressBar-bgColor-attention)",
  "--progressBar-bgColor-danger": "var(----progressBar-bgColor-danger)",
  "--progressBar-bgColor-done": "var(----progressBar-bgColor-done)",
  "--progressBar-bgColor-neutral": "var(----progressBar-bgColor-neutral)",
  "--progressBar-bgColor-severe": "var(----progressBar-bgColor-severe)",
  "--progressBar-bgColor-sponsors": "var(----progressBar-bgColor-sponsors)",
  "--progressBar-bgColor-success": "var(----progressBar-bgColor-success)",
  "--progressBar-track-bgColor": "var(----progressBar-track-bgColor)",
  "--reactionButton-selected-fgColor-rest":
    "var(----reactionButton-selected-fgColor-rest)",
  "--selectMenu-borderColor": "var(----selectMenu-borderColor)",
  "--selection-bgColor": "var(----selection-bgColor)",
  "--shadow-floating-legacy": "var(----shadow-floating-legacy)",
  "--shadow-inset": "var(----shadow-inset)",
  "--shadow-resting-medium": "var(----shadow-resting-medium)",
  "--shadow-resting-small": "var(----shadow-resting-small)",
  "--shadow-resting-xsmall": "var(----shadow-resting-xsmall)",
  "--tooltip-bgColor": "var(----tooltip-bgColor)",
  "--treeViewItem-leadingVisual-iconColor-rest":
    "var(----treeViewItem-leadingVisual-iconColor-rest)",
  "--underlineNav-iconColor-rest": "var(----underlineNav-iconColor-rest)",
  "--avatar-borderColor": "var(----avatar-borderColor)",
  "--border-closed-emphasis": "var(----border-closed-emphasis)",
  "--border-closed-muted": "var(----border-closed-muted)",
  "--border-muted": "var(----border-muted)",
  "--border-neutral-emphasis": "var(----border-neutral-emphasis)",
  "--border-open-emphasis": "var(----border-open-emphasis)",
  "--border-open-muted": "var(----border-open-muted)",
  "--border-upsell-emphasis": "var(----border-upsell-emphasis)",
  "--border-upsell-muted": "var(----border-upsell-muted)",
  "--borderColor-neutral-muted": "var(----borderColor-neutral-muted)",
  "--button-danger-bgColor-disabled": "var(----button-danger-bgColor-disabled)",
  "--button-danger-borderColor-rest": "var(----button-danger-borderColor-rest)",
  "--button-default-bgColor-disabled":
    "var(----button-default-bgColor-disabled)",
  "--button-default-borderColor-disabled":
    "var(----button-default-borderColor-disabled)",
  "--button-default-borderColor-rest":
    "var(----button-default-borderColor-rest)",
  "--button-default-fgColor-rest": "var(----button-default-fgColor-rest)",
  "--button-invisible-fgColor-active":
    "var(----button-invisible-fgColor-active)",
  "--button-invisible-fgColor-disabled":
    "var(----button-invisible-fgColor-disabled)",
  "--button-invisible-fgColor-hover": "var(----button-invisible-fgColor-hover)",
  "--button-invisible-fgColor-rest": "var(----button-invisible-fgColor-rest)",
  "--button-invisible-iconColor-disabled":
    "var(----button-invisible-iconColor-disabled)",
  "--button-outline-bgColor-disabled":
    "var(----button-outline-bgColor-disabled)",
  "--button-primary-borderColor-rest":
    "var(----button-primary-borderColor-rest)",
  "--button-primary-fgColor-rest": "var(----button-primary-fgColor-rest)",
  "--button-primary-iconColor-rest": "var(----button-primary-iconColor-rest)",
  "--control-checked-borderColor-disabled":
    "var(----control-checked-borderColor-disabled)",
  "--control-checked-borderColor-rest":
    "var(----control-checked-borderColor-rest)",
  "--control-checked-fgColor-rest": "var(----control-checked-fgColor-rest)",
  "--controlKnob-bgColor-disabled": "var(----controlKnob-bgColor-disabled)",
  "--controlKnob-bgColor-rest": "var(----controlKnob-bgColor-rest)",
  "--controlKnob-borderColor-checked":
    "var(----controlKnob-borderColor-checked)",
  "--controlKnob-borderColor-disabled":
    "var(----controlKnob-borderColor-disabled)",
  "--controlKnob-borderColor-rest": "var(----controlKnob-borderColor-rest)",
  "--controlTrack-fgColor-disabled": "var(----controlTrack-fgColor-disabled)",
  "--diffBlob-hunkNum-fgColor-hover": "var(----diffBlob-hunkNum-fgColor-hover)",
  "--focus-outline": "var(----focus-outline)",
  "--overlay-borderColor": "var(----overlay-borderColor)",
  "--tooltip-fgColor": "var(----tooltip-fgColor)",
  "--border-neutral-muted": "var(----border-neutral-muted)",
  "--button-danger-borderColor-hover":
    "var(----button-danger-borderColor-hover)",
  "--button-default-borderColor-active":
    "var(----button-default-borderColor-active)",
  "--button-default-borderColor-hover":
    "var(----button-default-borderColor-hover)",
  "--button-primary-borderColor-active":
    "var(----button-primary-borderColor-active)",
  "--button-primary-borderColor-hover":
    "var(----button-primary-borderColor-hover)",
  "--shadow-floating-large": "var(----shadow-floating-large)",
  "--shadow-floating-medium": "var(----shadow-floating-medium)",
  "--shadow-floating-small": "var(----shadow-floating-small)",
  "--shadow-floating-xlarge": "var(----shadow-floating-xlarge)",
  "--underlineNav-borderColor-hover": "var(----underlineNav-borderColor-hover)",
  "--button-danger-borderColor-active":
    "var(----button-danger-borderColor-active)",
  "--button-outline-borderColor-hover":
    "var(----button-outline-borderColor-hover)",
  "--button-outline-borderColor-active":
    "var(----button-outline-borderColor-active)",
};
